image: docker:latest
services:
  - docker:dind

#variables:
#  example: avoid pulling gitlab-runner-docker image from docker.io
#  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1
#  FF_NETWORK_PER_BUILD: 1
before_script:
#  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.epyc.tecnico.ulisboa.pt/ats/alpaca/alpaca-assets-kafka-to-postgresql.git".insteadOf git@gitlab.epyc.tecnico.ulisboa.pt/ats/alpaca/alpaca-assets-kafka-to-postgresql.git
  - echo "Cloning..."
  - git clone https://rato:${CI_JOB_TOKEN}@gitlab.epyc.tecnico.ulisboa.pt/ats/alpaca/alpaca-assets-kafka-to-postgresql.git

build:
  stage: build
  script:
    - echo "Cloning..."
    - git clone https://rato:${CI_JOB_TOKEN}@gitlab.epyc.tecnico.ulisboa.pt/ats/alpaca/alpaca-assets-kafka-to-postgresql.git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .

deploy:
   stage: deploy
   script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
   only:
    - main

# docker push gitlab.ideahub.duckdns.org:5050/alpha-equities/nasdaq/nasdaq-screener
